# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  node: circleci/node@5.2.0
  macos: circleci/macos@2

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    docker:
      - image: cimg/node:18.20
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1 ## no need to update homebrew
    steps:
      - checkout:
          path: ~/project
      - attach_workspace:
          at: ~/project
      - run:
          name: Install Softwares
          command: |
            sudo apt update
            sudo apt install libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev
            sudo apt install python3-pip
            sudo apt install uuid-dev clang llvm ninja-build
      - run:
          name: Install Premake
          command: |
            wget https://github.com/premake/premake-core/releases/download/v5.0.0-beta2/premake-5.0.0-beta2-linux.tar.gz
            tar -xvf premake-5.0.0-beta2-linux.tar.gz
            sudo chmod a+x premake5
            sudo mv premake5 /usr/local/bin/
          working_directory: ~/
      - run:
          name: Init submodules
          command: git submodule update --init --recursive
      - run:
          name: Build GLFW
          command: ./make_glfw.sh
          working_directory: ~/project/submodules/rive-cpp/skia/dependencies
      - run:
          name: Install Python PLY
          command: python3 -m pip install ply
      - run: 
          name: Build
          command: |
            export PATH="$PATH:$(pwd)/submodules/rive-cpp/build"
            build_rive.sh release
      - run:
          name: Build for WebGL2
          command: |
            export PATH="$PATH:$(pwd)/submodules/rive-cpp/build"
            build_rive.sh ninja wasm release

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  build-and-test:
    jobs:
      - build
